#!/bin/bash
PROJECT_NAME=spring-boot-admin
cd ${PROJECT_NAME}
git checkout master
git pull ${PROJECT_NAME} master && git push origin master
git fetch ${PROJECT_NAME} --tags master && git push origin master --tags
